######################## default configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL = "https://demo.gethugothemes.com/andromeda-light/site/"
# Title of your website (required).
title = "Andromeda-light - Software and SAAS Landing Hugo Theme"
# Your theme name
theme = "andromeda-light-hugo"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "America/New_York"
# post pagination
paginate = 4 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
# disable language
disableLanguages = [
] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage


########################### Services #############################
[services]
[services.googleAnalytics]
ID = 'G-MEASUREMENT_ID' # see https://gohugo.io/templates/internal/#configure-google-analytics

[services.disqus]
shortname = 'themefisher-template' # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/


########################## Permalinks ############################
[permalinks.page]
"pages" = "/:slugorfilename/"


############################# Modules ############################
[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"


############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/watching/hugo_stats\.json'
target = 'style\.css'
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = 'js'
[[build.cachebusters]]
source = 'assets/.*\.(css|scss|sass)'
target = 'css'
[[build.cachebusters]]
source = 'data/.*\.(.*)$'
target = 'css'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'


############################# Outputs ############################
[outputs]
home = ["HTML", "RSS", "WebAppManifest"]

############################# Imaging ############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "Lanczos"

############################ Caches ##############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################ Markup ##############################
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'monokai' # see https://xyproto.github.io/splash/docs/all.html

[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = true


########################### Media types ###########################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]


########################### Output Format ##########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"


######################### site variables ##############################
# customize your color and font from here.
[params.variables]
white = "#ffffff"
black = "#000000"
light = "#FAFAFA"
primary_color = "#FE6019"

# font variable
h1 = "48px"
h1_md = "38px"
h2 = "38px"
h2_md = "30px"
h3 = "22px"
h3_md = "20px"
h4 = "18px"
h5 = "16px"
h6 = "15px"
# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
primary_font = "Poppins:wght@400;500;600"
primary_font_type = "sans-serif" # [serif/sans-serif]
secondary_font = ""
secondary_font_type = "" # [serif/sans-serif]
icon_font = "Line Awesome Free"


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"
[[params.plugins.js]]
link = "plugins/rellax/rellax.min.js"
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
[[params.plugins.js]]
link = "plugins/cookie.js"
[[params.plugins.js]]
link = "plugins/glightbox/glightbox.js"
[[params.plugins.js]]
link = "js/gallery-slider.js"
[[params.plugins.js]]
link = "js/accordion.js"
[[params.plugins.js]]
link = "js/tab.js"
[[params.plugins.js]]
link = "js/modal.js"
[[params.plugins.js]]
link = "plugins/youtube-lite.js"
